name: CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    environment: testing
    runs-on: ubuntu-latest    
    # strategy:
    #   matrix:
    #     MY_VARIABLE: ['janit_v1', 'janit_v2']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # - name: Set Variable
      #   run: |
      #     echo "MY_VARIABLE=${{ matrix.MY_VARIABLE }}" >> $GITHUB_ENV
      - name: Build
        run: |
         npm pack
         ls
         pwd
         echo "Variable = ${{ secrets.SSH_KEY }}"
         ls -la
      - name: Decrypt Pem
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SSH_KEY" --output $HOME/secrets/my_private_key.pem my_private_key.pem.gpg
        env:
          SSH_KEY: ${{ secrets.SSH_KEY}}
      - name: List
        run: |
          ls
          ls -la
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: build-file
          path: .
      # - name: Checkout ansible
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ansible
      # - name: Run playbook
      #   run: ansible-playbook -i hosts playbook.yaml
