name: CI/CD
on: workflow_dispatch
jobs:
 build:
    environment: testing
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Checkout ansible
        run: git clone --single-branch --branch ansible https://github.com/janit-chawla/Nodejs-deploy.git
      - name: List
        run: ls
        # uses: actions/checkout@v4
        # with:
        #   ref: ansible
      - name: Build
        run: |
         npm pack
         ls
         pwd
         ls -la
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: build-file
          path: .
      - name: Download .tgz file
        uses: actions/download-artifact@v3
        with: build-file
      - name: List
        run: |
          ls -la
      - name: Decrypt Pem
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SSH_KEY" --output /home/runner/work/Nodejs-deploy/Nodejs-deploy/jan.pem /home/runner/work/Nodejs-deploy/Nodejs-deploy/Nodejs-deploy/jan.pem.gpg
        env:
          SSH_KEY: ${{ secrets.SSH_KEY}}
      - name: Change permission
        run: |
          chmod 600 jan.pem 
          ls | grep .tgz
          ls
      # - name: npm install
      #   run: npm install
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      # - name: List
      #   run: ls
      - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: 10.0.50.49:8081/repository/node-host/
        username: ${{ secrets.nxrm_user }}
        password: ${{ secrets.nxrm_password }}
        format: npm
        repository: node-host
        coordinates: groupId=com.example artifactId=app version=1.0.0
        assets: filename=gh-action-test
        filename: ./janit_v2-1.0.0.tgz
      - name: Run playbook
        run: ansible-playbook -i /home/runner/work/Nodejs-deploy/Nodejs-deploy/Nodejs-deploy/hosts /home/runner/work/Nodejs-deploy/Nodejs-deploy/Nodejs-deploy/playbook.yaml --private-key /home/runner/work/Nodejs-deploy/Nodejs-deploy/jan.pem -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
