name: CI/CD

on:
 push:
    branches:
      - main

jobs:
 build:
    environment: testing
    runs-on: ubuntu-latest    
    # strategy:
    #   matrix:
    #     MY_VARIABLE: ['janit_v1', 'janit_v2']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build
        run: |
         npm pack
         ls
         pwd
         echo "Variable = ${{ secrets.SSH_KEY }}"
         ls -la
      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: build-file
          path: .
      - name: Checkout ansible
        uses: actions/checkout@v4
        with:
          ref: ansible
      - name: List
        run: |
          ls
          ls -la
      - name: Decrypt Pem
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SSH_KEY" --output $HOME/secrets/jan.pem jan.pem.gpg
        env:
          SSH_KEY: ${{ secrets.SSH_KEY}}      
      - name: Run playbook
        run: ansible-playbook -i hosts playbook.yaml --private-key $HOME/secrets/jan.pem
